# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('method_name', models.CharField(max_length=100)),
                ('operation_name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HyperUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100, null=True, unique=True)),
                ('password', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('avatar', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('active', models.NullBooleanField()),
                ('boss', models.ForeignKey(blank=True, db_column='id_boss', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='user_management.HyperUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HyperUserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('type', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HyperUserGroupAPIResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.NullBooleanField()),
                ('api_resource', models.ForeignKey(blank=True, db_column='id_api_resource', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.HyperUserGroup')),
                ('user_group', models.ForeignKey(blank=True, db_column='id_user_group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='col_of_user_group_api', to='user_management.HyperUserGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
